(* ::Package:: *)

(* ::Input:: *)
(*(* DoAll.nb *)*)
(**)
(*(* This file runs all the files *)*)
(**)
(*(* Net worth data are used unless otherwise noted *)*)
(**)
(**)
(**)
(*ClearAll["Global`*"];*)
(**)
(**)
(**)
(**)
(**)
(*(* Models without aggregate shock *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Models without aggregate shock"];*)
(**)
(**)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggShocksDir]; *)
(**)
(*<<SolveAndSimPF.m;              (* Run PF rep agent and partial eq PF models *)*)
(**)
(**)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*NoAggShockDir    = Directory[] <> "/NoAggShock";    (* Directory where files without aggregate shock are saved *)*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[NoAggShockDir]; *)
(**)
(*<<FindBeta.m;                    (* Run model with point (unique) time pref factor and estimate \[Beta] *)*)
(**)
(*<<FindBetaDistSeven.m;           (* Run \[Beta]-Dist model with time pref factors approximated by seven points and estimate params *)*)
(**)
(**)
(**)
(*<<PlotCFuncandDeltaMZero.m;      (* Plots c func of the most patient and Delta m = 0 line *)*)
(**)
(*CFuncandDeltaMZeroPlot            (* Plot figure *)*)
(**)
(**)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*NoAggShockDir    = Directory[] <> "/NoAggShock";    (* Directory where files without aggregate shock are saved *)*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[NoAggShockDir]; *)
(**)
(*<<SolveAndSimKSNoAggShock.m;     (* Run KS-JEDC model without aggregate shock *)*)
(**)
(**)
(**)
(*(**)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*NoAggShockDir    = Directory[] <> "/NoAggShock";    (* Directory where files without aggregate shock are saved *)*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[NoAggShockDir]; *)
(**)
(*<<SolveAndSimKSHeteroNoAggShock.m;     (* Run KS-Hetero model without aggregate shock *)*)
(**)
(**)*)
(**)
(**)
(**)
(*<<PlotDistributionsWealthLevSCF_CastanedaAndDistSevenNoAggShock.m; *)
(**)
(*Print[" Figure of wealth distribution (without aggregate shock) "]; *)
(**)
(*CumWLevSCFCastanedaAndDistSevenNoAggShockPlot (* Plot *)*)
(**)
(**)
(**)
(*<<PlotDistributionsWealthLevSCF_CastanedaAndPointNoAggShock.m;*)
(**)
(**)
(**)
(**)
(**)
(*<<FindBetaDistSevenReiterOnly.m; (* Run \[Beta]-Dist model without simulations and estimate params *)*)
(**)
(*(**)
(**)
(*<<PlotWYRatioSCF_AndDistSeven.m; (* Plot US data and data generated using Reiter's (transition matrix) method *)*)
(**)
(*Print[" Plot wealth perm income ratios"];*)
(**)
(*WYRatioPlot (* Plot *)*)
(**)
(**)*)
(**)
(**)
(**)
(**)
(**)
(*(* Liquid FINANCIAL assets plus retirement assets *)*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*NoAggShockDir    = Directory[] <> "/NoAggShock";    (* Directory where files without aggregate shock are saved *)*)
(**)
(*SetDirectory[NoAggShockDir]; *)
(**)
(*<<FindBetaDistSevenLiqFinPlsRet.m;           (* Run \[Beta]-Dist model with time pref factors approximated by seven points and estimate params. Matching liquid FINANCIAL assets plus retirement assets. *)*)
(**)
(**)
(**)
(*<<PlotCFuncandDeltaMZeroLiqFinPlsRet.m; *)
(**)
(*PlotCFuncandDeltaMZeroLiqFinPlsRetPlot        (* plot *)*)
(**)
(**)
(**)
(**)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*NoAggShockDir    = Directory[] <> "/NoAggShock";    (* Directory where files without aggregate shock are saved *)*)
(**)
(*SetDirectory[NoAggShockDir]; *)
(**)
(*<<EstimateMoffittGottschalkProcess.m; *)
(**)
(**)
(**)
(**)
(**)
(**)
(**)
(*(* alt vars for KS point model *)*)
(**)
(*(* Models without aggregate shock *)*)
(**)
(*Print["============================================================="];*)
(**)
(*Print["Alt params"];*)
(**)
(*Print["Models without aggregate shock"];*)
(**)
(**)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*NoAggShockDir    = Directory[] <> "/NoAggShock";    (* Directory where files without aggregate shock are saved *)*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[NoAggShockDir]; *)
(**)
(**)
(**)
(*Print["High variance of tran shocks"];*)
(**)
(*<<FindBetaHighTran.m;                    (* Run model with point (unique) time pref factor and estimate \[Beta] *)*)
(**)
(**)
(**)
(*Print["High variance of perm shocks"];*)
(**)
(*<<FindBetaHighPerm.m;                    (* Run model with point (unique) time pref factor and estimate \[Beta] *)*)
(**)
(**)
(**)
(**)
(**)
(**)
(**)
(*(* Models with aggregate shocks *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Models with aggregate shocks"];*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggShocksDir]; *)
(**)
(*<<SolveAndSimKS.m;             (* Run rep agent and KS-JEDC model. Rep agent model is run as a first step. *)*)
(**)
(*Print[" Figure fCrossSectionVar "]*)
(**)
(*<<PlotfCrossSectionVar.m;      (* Plot fCrossSectionVar *)  *)
(**)
(*fCrossSectionVar*)
(**)
(**)
(**)
(*<<SolveAndSimKSHetero.m;       (* Run rep agent and KS-Hetero model. Rep agent model is run as a first step. *)*)
(**)
(*<<SolveAndSimPoint.m;          (* Run \[Beta]-Point model *)*)
(**)
(*Print[" Figure of consumption function"];*)
(**)
(*CFuncPointPlotALL *)
(**)
(**)
(**)
(*CFuncPointAndHistNetWorthPlot*)
(**)
(**)
(**)
(**)
(**)
(*<<FindBetaDistSeven.m;         (* Estimates parameter values for \[Beta]-Dist model (with aggregate shocks) *)*)
(**)
(*Print[" Matrix for \[EmptyDownTriangle]/3.5, \[Beta]middle, KLevMean, SumOfDevSq:"]; *)
(**)
(*StatsMat // MatrixForm*)
(**)
(*<<SolveAndSimDistSeven.m;      (* Run \[Beta]-Dist model with time pref factors approximated by seven points *)*)
(**)
(*Print[" Figure of consumption function"];*)
(**)
(*CFuncDistSevenPointAndHistNetWorthPlot*)
(**)
(**)
(**)
(*CFuncDistSevenAndHistNetWorthLiqFinPlsRetPlot*)
(**)
(**)
(**)
(*CFuncDistSevenPointAndHistNetWorthPlot*)
(**)
(**)
(**)
(**)
(**)
(*<<SolveAndSimKS_experiments.m; (* Run an experiment using KS-JEDC model *)*)
(**)
(*Print[" Figure of interst rate"]; *)
(**)
(*RPlot      *)
(**)
(*Print[" Figure of consumption growth"]; *)
(**)
(*dlAggCtPlot *)
(**)
(*<<PlotDistributionsWealthLevSCF_CastanedaAndDistSeven.m; *)
(**)
(*Print[" Figure of wealth distribution (with aggregate shocks) "]; *)
(**)
(*CumWLevSCFCastanedaAndDistSevenPlot   (* Plot *)*)
(**)
(**)
(**)
(**)
(**)
(*(* Liquid FINANCIAL assets plus retirement assets *)*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggShocksDir]; *)
(**)
(*<<FindBetaDistSevenLiqFinPlsRet.m;         (* Estimates parameter values for \[Beta]-Dist model (with aggregate shocks). Matching liquid FINANCIAL assets. *)*)
(**)
(*Print[" Matrix for \[EmptyDownTriangle]/3.5, \[Beta]middle, KLevMean, SumOfDevSq:"]; *)
(**)
(*StatsMat // MatrixForm*)
(**)
(*<<SolveAndSimDistSevenLiqFinPlsRet.m;      (* Run \[Beta]-Dist model with time pref factors approximated by seven points. Using parameter values estimated by matching liquid FINANCIAL assets plus retirement assets. *)*)
(**)
(**)
(**)
(**)
(**)
(*<<PlotDistributionsMPCsDistSevenKSAggShocks.m;*)
(**)
(*Print[" Figure of MPC comparison"];       (* Show distribution of MPCs when matching net worth and liq financial assets *)*)
(**)
(*DistributionsMPCsDistSevenAndKSKSAggShocksLiqFinPlsRetPlot (* Plot *)*)
(**)
(**)
(**)
(*(* Solve rep agent model with aggregate shocks *)*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggShocksDir]; *)
(**)
(*<<SolveAndSimRepAgent.m; *)
(**)
(**)
(**)
(**)
(**)
(*(* Models with alt params *)*)
(**)
(*Print["============================================================="];*)
(**)
(*Print["Alt params"];*)
(**)
(*Print["Models with aggregate shocks"];*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggShocksDir]; *)
(**)
(**)
(**)
(*Print["High variance of tran shocks"];*)
(**)
(*<<SolveAndSimPointHighTran.m;          (* Run \[Beta]-Point model *)*)
(**)
(**)
(**)
(*Print["High variance of perm shocks"];*)
(**)
(*<<SolveAndSimPointHighPerm.m;          (* Run \[Beta]-Point model *)*)
(**)
(**)
(**)
(**)
(**)
(**)
(**)
(**)
(**)
(*(* Models with aggregate PERMANENT shock *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Models with aggregate permanent shocks"];*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggPermShocksDir = Directory[] <> "/WithAggPermShocks"; (* Directory where files with PERMANENT aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggPermShocksDir]; *)
(**)
(**)
(**)
(*<<SolveAndSimPoint.m;      (* Run \[Beta]-Point model *)*)
(**)
(*<<SolveAndSimDistSeven.m;  (* Run \[Beta]-Dist model with time pref factors approximated by seven points *)*)
(**)
(**)
(**)
(*Print[" Figure of consumption function"];*)
(**)
(*CFuncDistSevenPointPermAndHistNetWorthPlot*)
(**)
(**)
(**)
(*CFuncDistSevenPermAndHistNetWorthLiqFinPlot*)
(**)
(**)
(**)
(*CFuncDistSevenPointPermAndHistNetWorthPlot*)
(**)
(**)
(**)
(*<<PlotDistributionsWealthLevSCF_CastanedaAndDistSevenPerm.m; *)
(**)
(*Print[" Figure of wealth distribution"]; *)
(**)
(*CumWLevSCFCastanedaAndDistSevenPermPlot (* Plot *)*)
(**)
(**)
(**)
(**)
(**)
(*(* Liquid FINANCIAL assets plus retirement assets *)*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggPermShocksDir = Directory[] <> "/WithAggPermShocks"; (* Directory where files with PERMANENT aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggPermShocksDir]; *)
(**)
(*<<SolveAndSimDistSevenLiqFinPlsRet.m;  (* Run \[Beta]-Dist model with time pref factors approximated by seven points. Using parameter values estimated by matching liquid FINANCIAL assets plus retirement assets. *)*)
(**)
(**)
(**)
(**)
(**)
(*<<PlotDistributionsMPCsDistSevenPerm.m;*)
(**)
(*Print[" Figure of MPC comparison"]; (* Show distribution of MPCs when matching net worth and liq financial assets *)*)
(**)
(*DistributionsMPCsDistSevenAndKSPermShocksLiqFinPlsRetPlot (* Plot *)*)
(**)
(**)
(**)
(**)
(**)
(*(**)
(**)
(**)
(**)
(*(* Robustness check: if people die at age 100 years  *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Robustness check: if people die at age 100 years "]*)
(**)
(**)
(**)
(*(* Models without aggregate shock *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Models without aggregate shock"];*)
(**)
(**)
(**)
(*(* Liquid FINANCIAL assets plus retirement assets *)*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*NoAggShockDir    = Directory[] <> "/NoAggShock";    (* Directory where files without aggregate shock are saved *)*)
(**)
(*SetDirectory[NoAggShockDir]; *)
(**)
(*<<FindBetaDistSevenLiqFinPlsRetDeathFrAge.m;           (* Run \[Beta]-Dist model with time pref factors approximated by seven points and estimate params. Matching liquid FINANCIAL assets plus retirement assets. *)*)
(**)
(**)
(**)
(*(* Models with aggregate PERMANENT shock *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Models with aggregate permanent shocks"];*)
(**)
(**)
(**)
(*(* Liquid FINANCIAL assets plus retirement assets *)*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggPermShocksDir = Directory[] <> "/WithAggPermShocks"; (* Directory where files with PERMANENT aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggPermShocksDir]; *)
(**)
(*<<SolveAndSimDistSevenLiqFinPlsRetDeathFrAge.m;  (* Run \[Beta]-Dist model with time pref factors approximated by seven points. Using parameter values estimated by matching liquid FINANCIAL assets plus retirement assets. *)*)
(**)
(**)
(**)
(**)
(**)
(**)
(**)
(*(* Robustness check with an ALTERNATIVE parameter for income shocks *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Robustness checks: Run \[Beta]-Dist model with an ALTERNATIVE parameter for income shocks"]*)
(**)
(*Print["Std of quarterly transitory shocks is 0.1 (half of the baseline)"]*)
(**)
(**)
(**)
(*(* Model without aggregate shock *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Model without aggregate shock"];*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*NoAggShockDir = Directory[] <> "/NoAggShock"; (* Directory where files without aggregate shock are saved *)*)
(**)
(*SetDirectory[NoAggShockDir]; *)
(**)
(*<<FindBetaDistSevenAltParamsLiqFinPlsRet.m;              (* Run \[Beta]-Dist model with time pref factors approximated by seven points and estimate params. Matching liquid FINANCIAL assets plus retirement assets. *)*)
(**)
(**)
(**)
(*(**)
(**)
(*(* Model with aggregate shocks *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Model with aggregate shocks"];*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggShocksDir = Directory[] <> "/WithAggShocks"; (* Directory where files with aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggShocksDir]; *)
(**)
(**)
(**)
(*<<FindBetaDistSevenAltParamsLiqFinPlsRet.m;         (* Estimates parameter values for \[Beta]-Dist model (with aggregate shocks). Matching liquid FINANCIAL assets. *)*)
(**)
(*Print[" Matrix for \[EmptyDownTriangle]/3.5, \[Beta]middle, KLevMean, SumOfDevSq:"]; *)
(**)
(*StatsMat // MatrixForm*)
(**)
(**)
(**)
(*<<SolveAndSimDistSevenAltParamsLiqFinPlsRet.m;    (* Run \[Beta]-Dist model with time pref factors approximated by seven points and estimate params. Matching liquid FINANCIAL assets plus retirement assets. *)*)
(**)
(**)
(**)
(**)*)
(**)
(**)
(**)
(*(* Model with aggregate PERMANENT shock *)*)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Model with aggregate permanent shocks"];*)
(**)
(*ClearAll["Global`*"];*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*WithAggPermShocksDir = Directory[] <> "/WithAggPermShocks"; (* Directory where files with PERMANENT aggregate shocks + file for PF rep agent are saved *)*)
(**)
(*SetDirectory[WithAggPermShocksDir]; *)
(**)
(*<<SolveAndSimDistSevenAltParamsLiqFinPlsRet.m;  (* Run \[Beta]-Dist model with time pref factors approximated by seven points and estimate params. Matching liquid FINANCIAL assets plus retirement assets. *)*)
(**)
(**)
(**)
(**)
(**)
(**)*)
(**)
(**)
(**)
(**)
(**)
(**)
(**)
(**)
(**)
(*(* Generate tables *)*)
(**)
(*(* This file generates tables in the paper. *)*)
(**)
(**)
(**)
(*Print["==========================================================================="];*)
(**)
(*Print["Generate tables "];*)
(**)
(*ClearAll["Global`*"];*)
(**)
(**)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*ResultsDir = Directory[] <> "/Results"; *)
(**)
(**)
(**)
(**)
(**)
(*(* produce tables for "cstKS" paper *)*)
(**)
(*SetDirectory[ResultsDir];*)
(**)
(*<<GenWDistcstKS.m;*)
(**)
(**)
(**)
(*SetDirectory[ResultsDir];*)
(**)
(*<<GenWDist_cstKSLarge.m;*)
(**)
(**)
(**)
(*SetDirectory[ResultsDir];*)
(**)
(*<<GenWDist_cstKSFull.m*)
(**)
(**)
(**)
(*SetDirectory[ResultsDir];*)
(**)
(*<<GenAggStatscstKS.m;*)
(**)
(**)
(**)
(*SetDirectory[ResultsDir];*)
(**)
(*<<GenMGComparison.m;*)
(**)
(**)
(**)
(**)
(**)
(*(* produce tables for "cstwMPC" paper *)*)
(**)
(*SetDirectory[ResultsDir]; *)
(**)
(*<<GenMPC.m;*)
(**)
(**)
(**)
(*SetDirectory[ResultsDir]; *)
(**)
(*<<GenMPCallRobustnessCheck.m; *)
(**)
(**)
(**)
(*SetDirectory[ResultsDir]; *)
(**)
(*<<GenMPC_scenarios.m;*)
(**)
(**)
(**)
(*SetDirectory[ResultsDir]; *)
(**)
(*<<GenMPCall_LCM.m; *)
(**)
(**)
(**)
(*(* produce other tables including for slides *)*)
(**)
(*SetDirectory[ResultsDir];*)
(**)
(*<<GenWDistslides.m;*)
(**)
(**)
(**)
(*SetDirectory[ResultsDir];*)
(**)
(*<<GenMPCslides.m;*)
(**)
(**)
(**)
(*SetDirectory[ResultsDir];*)
(**)
(*(**)
(**)
(*<<GenMPCslidesLiqFin.m;*)
(**)
(**)*)
(**)
(*<<GenMPCslidesLiqFinPlsRet.m*)
(**)
(**)
(**)
(*SetDirectory[ResultsDir]; *)
(**)
(*<<GenAggStatsPlausibleAggShocks.m;*)
(**)
(**)
(**)
(**)
(**)
(*(**)
(**)
(*<<GenTables.nb; *)
(**)
(* (* can run this file instead of producing all the table one by one *)*)
(**)
(**) *)
(**)
(**)
(**)
(*(**)
(**)
(*(* copy figures *)*)
(**)
(*SetDirectory[NotebookDirectory[]];*)
(**)
(*<<CopyFigures.m;*)
(**)
(**)*)
(**)
(*(* no need to do this under cstwMPC folder. commented this out on 2016/10/15 *)*)
(**)
(**)
